forge 'https://forge.puppetlabs.com'

mod 'puppetlabs/stdlib',      '4.6.0'
mod 'puppetlabs/apt',         '2.1.0'
mod 'puppetlabs/concat',      '1.2.3'
mod 'puppetlabs/firewall',    '1.4.0'
mod 'puppetlabs/inifile',     '1.3.0'
mod 'jfryman/nginx',          '0.2.7'
mod 'mayflower/php',          '3.2.2'
mod 'thias/postfix',          '0.3.3'
